; [pytest]
; python_files = *test.py
; markers = 
;     positive_test: толькопозитивные тесты
;     auth_test: тесты на авторизацию
;  python_fanctions = test_sum_positive_nums   

[pytest]
markers =
    positive: Тесты, которые проверяют корректное поведение функции
    negative: Тесты, которые проверяют некорректное поведение функции



# python_files = *test*.py
# python_functions = *sum*
# addopts = -v -s
# python_functions = test_div_by_zero
# python_classes = *Suites *Test
# python_files = chek_*
# python_functions = assert_*